import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Avatar from "../components/Avatar";

import { MicrophoneIcon, MoonIcon, ViewGridIcon } from "@heroicons/react/solid";
import { SearchIcon, SunIcon } from "@heroicons/react/outline";
import Footer from "../components/Footer";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/dist/client/router";
import { useTheme } from "next-themes";

const Home: NextPage = () => {
  const searchInputRef = useRef<HTMLInputElement>(null);

  const router = useRouter();
  const { theme, setTheme } = useTheme();
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  const search = (e: React.FormEvent) => {
    e.preventDefault();
    const term = searchInputRef?.current?.value;
    if (!term) return;
    router.push(`./search?term=${term}`);
  };
  return (
    <div className="dark:bg-[#202124] flex flex-col items-center justify-center h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex w-full p-5 justify-between text-sm ">
        <div className="flex space-x-4 items-center"></div>

        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Images</p>
          <button
            aria-label="Toggle Dark Mode"
            type="button"
            className="w-10 h-10 p-3 rounded focus:outline-none"
            onClick={() => setTheme(theme === "dark" ? "light" : "dark")}
          >
            {mounted && (
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                fill="currentColor"
                stroke="currentColor"
                className="w-4 h-4 text-yellow-500 dark:text-yellow-500"
              >
                {theme === "dark" ? (
                  <SunIcon className="h-12" />
                ) : (
                  <MoonIcon className="text-gray-600 h-10" />
                )}
              </svg>
            )}
          </button>

          <Avatar url="https://i.pinimg.com/280x280_RS/ab/a2/8e/aba28eb29f66aab5f24db128a0232f3f.jpg" />
        </div>
      </header>

      <form className="flex flex-col items-center mt-12 flex-grow w-4/5">
        <Image
          src="https://www.google.rw/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
          width={272}
          height={92}
          alt="Google logo"
        />
        <div className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border-[1px] border-[#dfe1e5] px-5 py-3 items-center sm:max-w-xl lg:max-w-2xl">
          <SearchIcon className="h-5 mr-3 text-gray-500 dark:text-white" />
          <input
            type="text"
            ref={searchInputRef}
            className=" focus:outline-none flex-grow bg-transparent"
          />
          <MicrophoneIcon className="h-5" />
        </div>
        <div className="flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm:space-x-4">
          <button onClick={search} className="btn">
            Google Search
          </button>
          <button onClick={search} className="btn">
            I`m feeling Lucky
          </button>
        </div>
      </form>

      <Footer />
    </div>
  );
};

export default Home;
